### PR TITLE
Working Refunds

### LINKED ISSUE #10: Refunding MVP
Currently, refunding isn't hooked up to the contract. We'll want to make it possible for contributors to vote to refund a proposal altogether.

- Hookup refund percentage to Progress component from Web3.
    -  Show green below 10% voting for refund, orange for 10% < voting < 40%, red for anything higher.
- Vote in favor of refund
- Retract vote in favor

Later
After the first pass, we can circle back and spec out a new issue that will also include vote justification, as well as functionality to allow proposal authors or team members to respond to contributor votes.

### PR DESCRIPTION
**Pull request by wbobeirne**
Closes #10.

### What This Does

Hooks up the refunding view under the governance tab. Allows users to see an up-to-date count of refund votes, make a vote if they've contributed, and receive their refund if the vote has passed.

### What Needs Work

Right now the contract is only refundable if it's "frozen," which only happens if someone runs the `refund` function after it's entered a state where it could be. This doesn't happen automatically, and I didn't build out a UI for allowing anyone to run this arbitrarily. Ideally the backend would automatically run this for everyone, rather than have a user do it.

Likewise, there are states where you can get a refund that aren't from a vote. A trustee could force a refund, or the deadline might pass. However, the refund UI only shows up in the case of a voted refund.

In general, all these states should auto-refund from the backend, rather than have users individually call it. Would like input (cc @dternyak) for how this PR should proceed.

### Steps to Test

* Start a proposal with account 1
* Have account 2 fund it by 40%, account 3 by 60%.
* Have account 2 vote for a refund. Confirm it shows up, but that you can't request a refund.
* Have account 3 vote for a refund. Confirm it shows up, and that both accounts can now request a refund.
* Have accounts 2 and 3 request a refund. Confirm it works.
* Confirm that a second refund cannot be requested.

### CODE REVIEW

**Comment by dternyak** [comment]
Very nice!

You're right on that we're getting to a place where a lot of these functions that need to be called behind the scenes are becoming blockers.

I've created https://github.com/grant-project/grant-monorepo/issues/33 and will try to hit it myself this week if no one else gets to it.

**Comment by wbobeirne** [comment]
The solution to the above case is that now, it'll hit the first person with two transactions. They'll be presented with this alert:

screen shot 2018-09-13 at 6 18 51 pm

And be prompted first to run `refund`, then to run their `withdraw`. If the former fails, they'll be notified that it's not actually in a refundable state.

**Comment by dternyak** [comment]
Awesome work! This is great.

I did notice a state that isn't covered:

As a trustee, I am able to refund the contract at any point, even before the deadline has passed.

This isn't reflected in the UI, instead the standard "Governance isn't available yet" view is shown.

screen shot 2018-09-13 at 7 45 29 pm

**Comment by dternyak** [comment]
I took a crack at implementing the ^ myself, but quickly realized that there will have to be a new screen where trustees can effectively "cancel" a crowdfund, which is a bit different than simply voting for refund like the others.

**Comment by dternyak** [comment]
Issue opened here https://github.com/grant-project/grant-monorepo/issues/44

**Pull request merged**
